defaults: &defaults
  cloud_name: hlbv2rjko
  api_key: <%= ENV['CLOUDINARY_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_SECRET'] %>
  enhance_image_tag: true
  static_image_support: false

production:
  <<: *defaults
development:
  <<: *defaults
test:
  <<: *defaults
